name: Build, Test and Lint

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - feature/*

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup latest version of node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'
    
      - name: Install dependancies
        run: |
          yarn install

      - name: Cache files
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ github.run_id }}

  build:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: .
        key: ${{ github.run_id }}

    - name: Build
      run: yarn  build

  esLint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: .
        key: ${{ github.run_id }}

    - name: Setup latest version of node
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'yarn'
  
    - name: Lint
      run: npx eslint .



  
    
