name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - feature/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
