name: 'Dependency Management'

on:
  schedule:
    - cron: '43 16 * * 2'
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  upgrade:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Upgrade Packages
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: upgrade --latest
        
    - name: Print branch name
      run: echo ${{ github.head_ref }}
    
    # Open a pull request if there are any changes
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        # token: ${{ secrets.GITHUB_TOKEN }}
        branch: update/yarn-upgrade
        base: ${{ github.head_ref }}
        title: Run yarn upgrade --latest
        commit-message: "chore(deps): Run yarn upgrade"
