name: 'Deploy to GitHub Pages'

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Set latest version of node
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'yarn'
    - name: Run Yarn Install
      run: yarn install