name: 'Deploy to GitHub Pages'

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Setup latest version of node
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'yarn'

    - name: Install dependancies and build
      run: |
       yarn install
       yarn build

    - name: Deploy
      run: |
        git init
        git checkout -B main
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:nathanhettige/starterkit.git main:gh-pages
      working-directory: ./dist



      

