name: 'Upgrade Dependencies'

on:
  schedule:
    - cron: '*/5 * * * *'
  pull_request:
    branches:
      - main

jobs:
  upgrade:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'yarn'

    - name: Upgrade Packages
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: upgrade --latest
    
    # Open a pull request if there are any changes
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: update/yarn-upgrade
        base: ${{ github.head_ref }}
        title: Package upgrades via Github Action
        commit-message: "Upgrades across major and/or minor versions via yarn"
